//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Kinect.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Kinect.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameter of type {0} not of of expected type {1}.
        /// </summary>
        internal static string DelegateCommandCastException {
            get {
                return ResourceManager.GetString("DelegateCommandCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All set!.
        /// </summary>
        internal static string MessageAllSet {
            get {
                return ResourceManager.GetString("MessageAllSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect is listening.
        /// </summary>
        internal static string MessageAllSetListening {
            get {
                return ResourceManager.GetString("MessageAllSetListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Kinect is being used by another application..
        /// </summary>
        internal static string MessageConflict {
            get {
                return ResourceManager.GetString("MessageConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops, there is an error..
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing....
        /// </summary>
        internal static string MessageInitializing {
            get {
                return ResourceManager.GetString("MessageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many USB devices! Please unplug one or more..
        /// </summary>
        internal static string MessageInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MessageInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect required.
        /// </summary>
        internal static string MessageNoAvailableSensors {
            get {
                return ResourceManager.GetString("MessageNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This sensor is not genuine!.
        /// </summary>
        internal static string MessageNotGenuine {
            get {
                return ResourceManager.GetString("MessageNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plug my power cord in!.
        /// </summary>
        internal static string MessageNotPowered {
            get {
                return ResourceManager.GetString("MessageNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kinect for Xbox not supported..
        /// </summary>
        internal static string MessageNotSupported {
            get {
                return ResourceManager.GetString("MessageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This application needs a Kinect for Windows sensor in order to function. However, another application is using the Kinect Sensor..
        /// </summary>
        internal static string MoreInformationConflict {
            get {
                return ResourceManager.GetString("MoreInformationConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Kinect Sensor is plugged in, however an error has occurred. For steps to resolve, please click the &quot;Help&quot; link..
        /// </summary>
        internal static string MoreInformationError {
            get {
                return ResourceManager.GetString("MoreInformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Kinect Sensor needs the majority of the USB Bandwidth of a USB Controller. If other devices are in contention for that bandwidth, the Kinect Sensor may not be able to function..
        /// </summary>
        internal static string MoreInformationInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MoreInformationInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNoAvailableSensors {
            get {
                return ResourceManager.GetString("MoreInformationNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This application needs a genuine Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNotGenuine {
            get {
                return ResourceManager.GetString("MoreInformationNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Kinect Sensor is plugged into the computer with its USB connection, but the power plug appears to be not powered..
        /// </summary>
        internal static string MoreInformationNotPowered {
            get {
                return ResourceManager.GetString("MoreInformationNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNotSupported {
            get {
                return ResourceManager.GetString("MoreInformationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to launch the default web browser. Trying to navigate to: {0}.
        /// </summary>
        internal static string NoDefaultBrowserAvailable {
            get {
                return ResourceManager.GetString("NoDefaultBrowserAvailable", resourceCulture);
            }
        }
    }
}
